# Generated by Django 5.1.1 on 2025-02-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
